### ISSUE TITLE
calculate images overlays

### ISSUE THREAD

**Issue by romsson** [centralelyon/ntt#9]
given 2 or more images, we want to generate a single image that is the overlay of all images:

parameters:
- opacity parameter for each image
- boolean operations: union, difference, xor, etc. (default should be union)

the result should be a new image (as an np array)

**Comment by faroukmiled** [comment]
I extended this feature to videos.

Given two videos with same width, height and fps, overlay them into a single video.
parameters : 

- path_videos (string) : path to the videos.
- video_name1 (string) : name of the first video.
- video_name2 (string) : name of the second video.
- video_out (string) : name of the output video.
Output : 
    - video which is the overlay of the two input videos.

https://github.com/centralelyon/ntt/blob/9-calculate-images-overlays/samples/overlayed_points.mp4
